config/routes.rb
GkoAdvisaCom::Application.routes.draw do
  resources :contacts, :to => 'contacts#create', :only => :create
end

app/models/contact.rb
class Contact < MailForm::Base
  attributes :civility, :validate => true
  attributes :lastname, :validate => true
  attributes :firstname, :validate => true
  attributes :email, :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attributes :phone, :validate => true
  attributes :country, :validate => true
  attributes :company
  attributes :professional
  attributes :message
  attributes :nickname, :captcha => true
  
  validates :email, :presence => true, :email => true
  
  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "Contact from website",
      :to => Site.current.preferred_contact_email,
      :from => %("#{lastname}" <#{email}>)
    }
  end
  
end

app/controllers/contacts_controller.rb
# app/controllers/contacts.rb
class ContactsController < BaseController
  def new
    @page = site.sections.find_by_template('contact')
    @contact = Contact.new
    respond_with(@contact, :template => 'pages/contact')
  end

  def create
    begin
      @page = site.sections.find_by_template('contact')
      @contact = Contact.new(params[:contact])
      @contact.request = request
      if @contact.deliver
        flash.now[:notice] = 'Thank you for your message!'
        respond_with(@contact, :template => 'pages/contact')
      else
        respond_with(@contact, :template => 'pages/contact')
      end
    rescue ScriptError
      flash[:error] = 'Sorry, this message appears to be spam and was not delivered.'
    end
  end

end

app/views/application/_footer.html.erb
<% cache([site, I18n.locale, 'footer2']) do %>
<!-- Footer
================================================== -->
 <footer id='footer-container' class='container-fluid footer hide-on-print'>
   <div id='footer' class='row-fluid'>
     <div class="span12 footer-content">
		<%= render_menu('pipe') %>
     </div>
   </div>
 </footer>
<% end %>

app/views/application/_header.html.erb
<% cache([site, I18n.locale, 'header5']) do %>
<!-- Header
================================================== -->
<header class="navbar hide-on-print">
  <div class="navbar-inner">
    <div class="row-fluid">
      <div class="header-top">
        <%= render_menu('tools') %>
        <%= render 'locales_select' %>
      </div>
      <div class="header-nav">
        <!-- Be sure to leave the brand out there if you want it shown -->
        <%= render 'site_title' %>
        <%= content_tag(:h4, site.subtitle.html_safe, :id => "site-subtitle") if site.subtitle.present? %>
        <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span><%= t(:navigation_menu) %><i class="icon-chevron-down icon-white"></i></span>
        </a>
        <!-- Everything you want hidden at 940px or less, place within here -->
        <div class="nav-collapse">
          <!-- .nav, .navbar-search, .navbar-form, etc -->
          <%= render "primary_menu" %>
        </div>
      </div>

    </div>
  </div>
</header>
<% end %>

app/views/layouts/application.html.erb
<!doctype html>
<%= render 'html_tag' %>
<%= render 'head' %>
<body id='<%= @body_id %>'>
<!--[if lt IE 7]><p class=chromeframe>Your browser is <em>ancient!</em> <a href="http://browsehappy.com/">Upgrade to a different browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a> to experience this site.</p><![endif]-->
<div id="wrapper-wide-body">
  <%= render 'header' %>

  <div id='main-container' class='container-fluid'>

    <% if content_for?(:page_container) %>
        <%= render "flash" %>
        <%= yield :page_container %>
    <% else %>
		<% if content_for?(:slideshow) %>
			<%= yield :slideshow %>
	 	<% end %>
        <div id="main-row" class='row-fluid'>
          <% if content_for?(:page_content) %>
              <div id="main" class='span12 <%= @body_id %>'>
				<%= yield :page_content %>
              </div>
          <% else %>
              <%
                 has_left_sidebar = content_for?(:left_sidebar)
                 has_sidebar = content_for?(:sidebar_header) || content_for?(:sidebar)
                 main_span = 12
                 main_span -= 3 if has_sidebar
                 main_span -= 3 if has_left_sidebar
              %>
              <% if has_left_sidebar %>
                  <aside id='left_sidebar' class="span3"><%= yield :left_sidebar %></aside>
              <% end %>
              <div id="main" class='span<%= main_span %> <%= @body_id %> '>
				  
                  <%= yield %>
              </div>
              <% if has_sidebar %>
                  <aside id='sidebar' class="span3">
					<%= yield :sidebar_header %>
					<%= yield :sidebar %>
                  </aside>
              <% end %>
          <% end %>
        </div>
        <% end %><%# end page_container %>
  </div>
  <%= render 'footer' %>
  <%= render 'copyright' %>
</div>

<%= render 'javascripts' %>
</body>
</html>

app/views/pages/_resource.html.erb
<% content_for :slideshow do %>
	<div class="row-fluid"> 
		<div class="span12">
			<%= render "images/carousel", :images => resource.images, :image_style => site.preferred_image_carousel_size %>
		</div>
	</div>
<% end if resource.images.try(:any?) %>
<% resource_cache(resource) do %>
	<div class="row-fluid"> 
		<div class="span12">
			<%= render_page_title(resource.title) %>
			<%= render_html_text(resource.body) %>
		</div>
	</div>
<% end %>

app/views/pages/contact.html.erb
<% content_for :slideshow do %>
	<div class="row-fluid"> 
		<div class="span12">
			<%= render "images/carousel", :images => @page.images, :image_style => site.preferred_image_carousel_size %>
		</div>
	</div>
<% end if @page.images.try(:any?) %>
<% resource_cache(resource) do %> 
<div class="row-fluid">
	<div class="span12">
		<%= render_page_title(@page.title) %>
	</div>
</div>
<div class="row-fluid">
	<div class="span6 html-text">
		<%= render_html_text(@page.body) %>
	</div>
	<div class="span6 html-text">
		<p><%= t("contact_us_infos") %></p>
    <% @contact = Contact.new() unless @contact %>
		<%= simple_form_for(@contact, :url => contacts_path, :method => :post, :html => {:class => [:'form-horizontal']}) do |f| %>
		    <%= hidden_field_tag(:return_to, @page.public_url) %>
        <%= @contact.errors.full_messages.to_s %>
		    <%= f.input :civility, 
						:collection => t("civilities"),
						:hint => false,
						:required => true %>
			<%= f.input :lastname, 
						:hint => '' %>						
			<%= f.input :firstname, 
						:hint => false %>
            <%= f.input :professional,
            :as => :boolean,
            :hint => false,
            :required => false %>
      <%= f.input :company, 
            :hint => false,
            :required => false %>
		    <%= f.input :email, 
						:hint => false %>
		    <%= f.input :phone, 
						:hint => false,
						:required => false %>
        <%= f.input :country,
          :hint => false,
          :required => false %>
		    <%= f.input :message, 
						:as => :text, 
						:hint => false, 
						:input_html => {:rows => 6} %>
			<%= f.input :nickname, 
						:as => :hidden,
						:hint => 'Leave this field blank!' %>
		    <div class='controls'>
		      <%= f.button :submit, t("send_inquiry"), :class => 'btn btn-block btn-large btn-inverse', :disable_with => "Submitting..." do %>	<i class="icon-arrow-right"></i>
			<% end %>
			</div>
		<% end %>
		<p><small><em><%= raw t(:inquiry_ps) %></em></small></p>
	</div>	
</div>
<% end %>

app/views/pages/home.html.erb
<%= render 'pages/resource', :resource => site.home %>

app/views/pages/member_access.html.erb
<% resource_cache(resource) do %>
<article class="member-access"> 
	<div class="row-fluid">
		<div class="span12">
			<%= render_page_title(resource.title) %>
		</div>
	</div>
	<div class="row-fluid">
		<div class="span8">
			<%= render_html_text(resource.body) %>
		</div>
		<div class="span4">
			<%= simple_form_for :user, 
								:url => user_session_path, 
								:html => { :data => { :remote => true, :type => :json }, :id => "signin-form" } do |f| %>
				<%= f.input :email, :placeholder => "Your Email Address", :label => false, :hint => false %>
				<%= f.input :password, :placeholder => "Your Password", :label => false, :hint => false %>
				<%= f.button :submit, t("member_access_submit"), :class => 'btn btn-block btn-large btn-inverse', :disable_with => "Submitting..." do %>
						<i class="icon-arrow-right"></i>
				<% end %>
			<% end %>
		</div>
	</div>
</article>
<% end %>

app/views/pages/sitemap.html.erb
<%= render_slideshow_for(resource) %>
<%= render_page_title(resource.title) %>
<%= render_html_text(resource.body) %>
<div class="row-fluid">
  <div class="span6">
    <%= render "sitemap" %>
  </div>
  <div class="span6">
    <%= image_tag("sitemap.jpg") %>
  </div>
</div>